# Generated by Django 5.2.13 on 2026-04-21 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
